# Generated by Django 4.2.30 on 2026-06-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsample',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
