# Generated by Django 4.2.30 on 2026-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projectsample_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsample',
            name='image',
        ),
        migrations.AddField(
            model_name='projectsample',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
