# Generated by Django 6.0.6 on 2026-06-05 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='max_history',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='last_picked',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last picked'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='times_picked',
            field=models.IntegerField(default=0),
        ),
    ]
