# Generated by Django 6.0.6 on 2026-06-08 18:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0003_player_choice_tournament_player_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='uid',
        ),
        migrations.AddField(
            model_name='tournament',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='final_choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chooser.item'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='lifespan',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
