# Generated by Django 6.0.6 on 2026-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0004_remove_tournament_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
