# Generated by Django 6.0.6 on 2026-06-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0005_player_turn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
