# Generated by Django 6.0.6 on 2026-06-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0006_tournament_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
