# Generated by Django 6.0.6 on 2026-06-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0007_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='final_choice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chooser.item'),
        ),
    ]
