# Generated by Django 6.0.6 on 2026-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0008_alter_tournament_final_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='num_players',
            field=models.IntegerField(default=1),
        ),
    ]
