# Generated by Django 4.2.30 on 2026-06-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0009_tournament_num_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='method',
            field=models.CharField(choices=[('simple', 'simple'), ('tournament', 'tournament')], default='tournament', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='weighting',
            field=models.CharField(choices=[('uniform', 'uniform'), ('seeded', 'seeded'), ('strong', 'strong'), ('weak', 'weak')], default='seed', max_length=10),
        ),
    ]
