# Generated by Django 4.2.30 on 2026-06-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='source',
        ),
    ]
