# Generated by Django 4.2.30 on 2026-06-22 21:38

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_photo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to='photos/'),
        ),
    ]
