# Generated by Django 4.2.30 on 2026-06-19 22:39

from django.db import migrations, models
import core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_photo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=core.storages.CustomS3Storage(), upload_to='photos/'),
        ),
    ]
