# Generated by Django 4.2.30 on 2026-06-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
    ]
