# Generated by Django 4.2.30 on 2026-06-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photoproject_alter_photo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
