# Generated by Django 4.2.30 on 2026-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoproject',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
