# Generated by Django 4.2.30 on 2026-06-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_photoproject_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='photo.photoproject'),
        ),
    ]
